### ISSUE TITLE
Changing a user from admin to nonadmin does not force them to also upload a signature

### ISSUE THREAD

**Issue by mcmattmclean** [So-hu/emp-portal#44]
You can create an admin user, then switch to nonadmin to get around adding a signature. This user will not have emails sent for their awards until they manually add a signature.

**Comment by mcmattmclean** [comment]
I may just disable the ability to change user type, as this also prevents an admin from breaking their own or other admin's accounts.

**Comment by edwin03** [comment]
I agree with you.
